# Generated by Django 2.2.2 on 2019-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='combos/files/')),
                ('lowerbound', models.IntegerField()),
                ('upperbound', models.IntegerField()),
            ],
        ),
    ]
